### ISSUE TITLE
Examples of Wavetable synthesizer model for training

### ISSUE THREAD

**Issue by skokoh** [magenta/ddsp#164]
May I ask you about some examples of Wavetable synthesizer for training?

I am trying to write down a customized wavetable synthesizer model (not additive synthesizer), but posted "gin" files are targeting additive synthesizer only. I can see some examples of wavetable synthesizer in synths_test.py or tutorials, but processor_group.ipynb also covers additive synthesizer example, not wavetable version. If you could share more examples of other synthesizers (not additive), it would be appreciated. Thank you!

**Comment by jesseengel** [comment]
Hi! 

We don't actually have any examples of training with a wavetable synthesizer because I haven't had time to try it :). The last colab notebook tutorial has some example usage, so I know the algorithm works, (albeit with some aliasing from the linear interpolation method). You would need to work out a good network architecture for specifying a series of wavetables in time, which actually is the same thing the additive synth is doing, but additive is in the frequency domain, while wavetable is in the time domain. Sorry I don't have more to work with, but this is an area of ongoing research and just so many projects to do :). If you find something that works for you feel free to submit a PR.

All the best,
Jesse
