### ISSUE TITLE
Checkpoints for piano (and connect it to piano transcriber)

### ISSUE THREAD

**Issue by mathigatti** [magenta/ddsp#220]
Hi, anyone trained it for piano? I'm not sure if it makes sense, but since you already developed a great [piano transcriber](https://magenta.tensorflow.org/onsets-frames), then if you are able to change the timbre of any instrument to a piano then it will be possible to transcribe any instrument to MIDI with a descent quality.

I think that would be really useful for creating good quality datasets for singing synthesis easily for example.

**Comment by jesseengel** [comment]
That's an interesting idea for semi-supervision. The basic harmonic models are not actually a great fit for pianos at the moment because pianos have multiple strings per a note and stiff strings that make the upper harmonics not integer multiples. We are working on some more expressive models currently and will let you know how that goes.

**Comment by mathigatti** [comment]
Makes sense. Thank you very much for the answer, I will keep an eye on your updates :)
