### ISSUE TITLE
Parameters collapsing in training notebook

### ISSUE THREAD

**Issue by zqevans** [magenta/ddsp#286]
I've been trying to get the [training example notebook](https://colab.research.google.com/github/magenta/ddsp/blob/master/ddsp/colab/tutorials/3_training.ipynb) to work so I can build off of that for other ideas I have. However, the last few times I've tried to run it, it ends up essentially training silence. The harmonic synth and the noise synth are both almost zeroed out.

Is this bad luck on my part, or is there something causing issues with performance in that notebook, or in the library overall right now?

I also had to make some adjustments to the notebook to get it to run, since the notebook is referencing `F0LoudnessPreprocessor`, but it still needs to be `DefaultPreprocessor`. So I'm not sure if the version mismatch is causing issues.

Another note, I set `shuffle=True` in the line `dataset = data_provider.get_batch(batch_size=1, shuffle=True).take(1).repeat()` so that I could get something other than the initial NSynth data point that it was always giving me.

**Comment by jesseengel** [comment]
Sorry for the confusion, the Preprocessor issue is addressed in #293. In general, fitting the parameters of the model to a single data example (as is done in the notebook) is not as robust as training on a full dataset, as the optimization benefits from the stochasticity of minibatches I think. We chose that initial NSynth data point just as an instructional point because we saw that it fit okay, but for more general training, you would want to try a bigger dataset and batch size.
