### ISSUE TITLE
Can't parse serialized Example when loading data

### ISSUE THREAD

**Issue by james20141606** [magenta/ddsp#36]
Hey, I am trying to run codes in train_autoencoder.ipynb and I got the following error after running `next(iter(dataset))`
InvalidArgumentError: Key: audio.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]

I change some of the ddsp_prepare_tfrecord configs since my audio is usually less than 1 sec:
```
!ddsp_prepare_tfrecord \
    --input_audio_filepatterns=$AUDIO_FILEPATTERN \
    --output_tfrecord_path=$TRAIN_TFRECORD \
    --num_shards=1 \
    --example_secs 1 \
    --sliding_window_hop_secs 0.25 \
    --alsologtostderr
```

I am not sure what went wrong. I could find the dataset contains: <ParallelMapDataset shapes: {audio: (64000,), f0_confidence: (1000,), f0_hz: (1000,), loudness_db: (1000,)}, types: {audio: tf.float32, f0_confidence: tf.float32, f0_hz: tf.float32, loudness_db: tf.float32}>

**Comment by james20141606** [comment]
If I rerun it and set num_shards=1 to 2 or 10, I will get different errors with respect to different keys including f0_hz and loudness_db.

**Comment by james20141606** [comment]
It's really interesting, I just use the violin example with time length around 3 mins and it was processed correctly. It seems the time length of single audio file does matter? I am not sure if concatenating single audio files in a large audio file could fix the problem?

**Comment by jesseengel** [comment]
Hi, I think you're running up against some edge cases because you're trying to create a dataset out so little audio. The models tend to overfit on several minutes of audio, so it doesn't really make much sense to make a dataset and train on so little audio. We make several shards to improve dataset read times for training. So, first off, in all honesty I'd suggest just getting some more data to train on. I'm not sure what the lower limit is, but I think at least 1 minute should suffice.

For fun, if you want to see what a model is like training on a single example you could try loading your audio directly (using ddsp.colab.colab_utils.upload) and training in the tutorial colab [3_training.ipynb](https://github.com/magenta/ddsp/blob/master/ddsp/colab/tutorials/3_training.ipynb).

**Comment by james20141606** [comment]
Thx for the explanation!
