### ISSUE TITLE
pip stuck looking for compatible dependencies

### ISSUE THREAD

**Issue by Moxinilian** [magenta/ddsp#376]
Hello!

When installing ddsp via pip, it seems to struggle a lot on every single dependency, downloading tens of versions to "determine which version is compatible with other requirements." Unfortunately it is prohibitively long on my machine, after a night resolving it still was not done. Would you have any idea of what is going on?

Thanks in advance!

**Comment by Moxinilian** [comment]
When trying installing the project using setup.py, it explains that h5py 3.1.0 is fetched but crepe requires h5py<3.0.0

**Comment by yeeking** [comment]
Hello! I had this problem. Figured out that it was because I was on Python 3.9 in Ubuntu 21.04. The solution I found was to use pyenv to install an older version of Python. I went for 3.7.0. Here's how I did it:

First off, set up libs so that the python you are about to build has the right stuff for ddsp:

```
sudo apt install libbz2-dev libssl-dev liblzma-dev
```

Install pyenv:
https://github.com/pyenv/pyenv-installer

https://stackoverflow.com/questions/59549829/how-do-i-downgrade-my-version-of-python-from-3-7-5-to-3-6-5-on-ubuntu

```
curl https://pyenv.run | bash

# install 3.7.0
~/.pyenv/bin/pyenv install 3.7.0
# activate 3.7.0
~/.pyenv/bin/pyenv local 3.7.0
# create a virtual env with 3.7.0
~/.pyenv/bin/pyenv virtualenv myvirtualenv
# activate it 
~/.pyenv/bin/pyenv activate myvirtualenv
# verify python version
python --version
Python 3.7.0
# go for it!
pip install ddsp
# I found this installed TF 2.4 so I also upgraded that
pip install --upgrade tensorflow
# finally:
python
import ddsp
ddsp.__version__
1.2.0

```

**Comment by Moxinilian** [comment]
Incredible, it worked! Thank you very much. I also had to upgrade pip before attempting to install ddsp.
